spring:
  application:
    name: moduplaylist-realtime



server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: mopl

realtime:
  sse:
    timeout-millis: ${SSE_TIMEOUT_MILLIS:1800000} # SSE 기본 30 분
  kafka:
    notification-consumer-group: notification-sse
    dm-message-consumer-group: dm-websocket-${REALTIME_INSTANCE_ID:${random.uuid}}
