spring:
  application:
    name: moduplaylist-api

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 55MB

  profiles:
    active: dev

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        hikaricp.connections.acquire: true
        hikaricp.connections.usage: true

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: mopl
    access-token-validity-seconds: 3600 # 1시간
    refresh-token-validity-seconds: 86400 # 1일
    cookie-secure: ${JWT_COOKIE_SECURE:true}
