spring:
  application:
    name: moduplaylist-api

  profiles:
    active: dev

server:
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: mopl
    access-token-validity-seconds: 3600 # 1시간
    refresh-token-validity-seconds: 86400 # 1일
    cookie-secure: ${JWT_COOKIE_SECURE:true}