spring:
  datasource:
    # example address
    url: ${DB_URL:jdbc:mysql://localhost:3306/moduplaylist}
    username: ${DB_USERNAME:mopl}
    password: ${DB_PASSWORD:mopl}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  batch:
    job:
      enabled: false
      #name: contentEmbeddingJob

  ai:
    model:
      chat: none
      embedding: openai
    openai:
      api-key: ${OPENAI_API_KEY:}
      embedding:
        options:
          model: text-embedding-3-small

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.moduplaylist.infrastructure.kafka.event

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3:
   region: ${AWS_REGION:ap-northeast-2}
   bucket: ${AWS_S3_BUCKET:}

mopl:
  batch:
    embedding:
      scheduler:
        enabled: ${EMBEDDING_SCHEDULER_ENABLED:false}
        content-cron: ${CONTENT_EMBEDDING_CRON:0 0 2 * * *} #실제 배치 실행 시간
#        content-cron: "0 * * * * *" #테스트
        user-profile-cron: ${USER_PROFILE_EMBEDDING_CRON:0 0 3 * * *} #실제 배치 실행 시간
#        user-profile-cron: "0 * * * * *" #테스트
        zone: ${EMBEDDING_SCHEDULER_ZONE:Asia/Seoul}
    recommendation:
      activity-batch-size: ${RECOMMENDATION_ACTIVITY_BATCH_SIZE:500}
      scheduler:
        enabled: ${RECOMMENDATION_SCHEDULER_ENABLED:false}
        cron: ${RECOMMENDATION_CRON:0 0 4 * * *}
#        cron: "0 * * * * *" #테스트
        zone: ${RECOMMENDATION_SCHEDULER_ZONE:Asia/Seoul}
  recommendation:
    search-limit: ${RECOMMENDATION_SEARCH_LIMIT:100}
    cache-ttl: ${RECOMMENDATION_CACHE_TTL:48h}
  embedding:
    enabled: ${EMBEDDING_ENABLED:true}
    model: text-embedding-3-small
    dimensions: 1536
  opensearch:
    enabled: ${OPENSEARCH_ENABLED:true}
    uris: ${OPENSEARCH_URIS:http://localhost:9200}
    username: ${OPENSEARCH_USERNAME:}
    password: ${OPENSEARCH_PASSWORD:}
    user-preference-index: user-preference-index
    content-index: content-index
